#Numpy Assignment_1

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


In [2]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [3]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

print("Data types of each element in list_:")
for element in list_:
    print(type(element))

print("Data types of each element in array_list:")
for element in array_list:
    print(type(element))


Data types of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
# Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int). Will there be any difference in the data type of the elements present in both the variables, list_ and array_list?
# If so then print the data types of each and every element present in both the variables, list_ and array_list.
# After converting array_list to an integer type, the elements of array_list will be of type int, while the elements of list_ will remain as strings
# Q3
array_list = np.array(object=list_, dtype=int)

print("Data types of each element in list_:")
for element in list_:
    print(type(element))

print("Data types of each element in array_list:")
for element in array_list:
    print(type(element))


Data types of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size
# Q4
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

In [6]:
# Q5. Write a code to create numpy array of 3x3 matrix containing zeros only, using a numpy array creation function.
# Q5
zero_matrix = np.zeros((3, 3))
print("3x3 matrix containing zeros only:\n", zero_matrix)


3x3 matrix containing zeros only:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions
# Q6
identity_matrix = np.eye(5)
print("Identity matrix of shape (5,5):\n", identity_matrix)


Identity matrix of shape (5,5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
